add release workflows

diff --git a/.github/wordflows/test-build.yaml b/.github/wordflows/test-build.yaml
--- a/.github/wordflows/test-build.yaml
+++ b/.github/wordflows/test-build.yaml
@@ -1,24 +1,35 @@
-name: Test Build
+name: Test Build Process without releasing
 
 on:
-  pull-request:
-  workflow_call:
+  push:
+    paths:
+      - '.github/workflows/**.yml'
 
 jobs:
-  build:
-    name: build
-    matrix:
-      os: [ ubuntu-latest, windows-latest ]
-    runs-on: ${{ matrix.os }}
+  read-version-string:
+    name: "Read Version String from Maven project.version"
+    runs-on: ubuntu-latest
+    outputs:
+      project_version: ${{ steps.step1.outputs.project_version }}
     steps:
       - uses: actions/checkout@v4
-      - name: Set up JDK
-        uses: actions/setup-java@v4
-        with:
-          java-version: '23'
-          distribution: 'temurin'
-          cache: maven
-      - name: Build with Maven
+      - id: step1
+        name: "Read Version String and write to output"
         run: |
-          ./mvnw --batch-mode --update-snapshots package 
-          ./mvnw --batch-mode jpackage:jpackage
+          project_version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
+          # fail, if version is not a valid version string (mvn outputs "null object or invalid expression")
+          if [[ "$project_version" = "null object or invalid expression" ]]; then
+              echo "Could not determine project version. Output was: $project_version"
+              echo "Aborting"
+              exit 1
+          fi
+          echo "${project_version}"
+          echo "project_version=${project_version}" >> "$GITHUB_OUTPUT"
+
+  build:
+    name: Build to test
+    needs: read-version-string
+    uses: ./.github/workflows/build.yml
+    with:
+      version: ${{ needs.read-version-string.outputs.project_version }}
+    secrets: inherit
